# Generated by Django 5.1.2 on 2024-11-10 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dadosQuiz', '0003_alternativa_questoes_resultado'),
    ]

    operations = [
        migrations.AddField(
            model_name='alternativa',
            name='correta',
            field=models.BooleanField(default=False),
        ),
    ]
