# Generated by Django 5.1.2 on 2024-11-30 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dadosQuiz', '0008_remove_resultado_correta_remove_resultado_questoes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questoes',
            options={'verbose_name': 'Questão', 'verbose_name_plural': 'Questões'},
        ),
    ]
