# Generated by Django 5.1.2 on 2024-11-10 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alternativa_correta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternativa',
            name='Questoes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternativa', to='core.questoes'),
        ),
    ]
