# Generated by Django 5.1.2 on 2024-11-10 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_resultado_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alternativa',
            old_name='Questoes',
            new_name='questoes',
        ),
        migrations.RenameField(
            model_name='questoes',
            old_name='Assunto',
            new_name='assunto',
        ),
        migrations.RenameField(
            model_name='resultado',
            old_name='Questoes',
            new_name='questoes',
        ),
        migrations.AddField(
            model_name='resultado',
            name='resposta_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respostas_usuario', to='core.alternativa'),
        ),
    ]
