# Generated by Django 5.1.2 on 2024-11-10 21:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_questoes_alternativa_questoes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultado',
            name='correta',
        ),
        migrations.RemoveField(
            model_name='resultado',
            name='questoes',
        ),
        migrations.RemoveField(
            model_name='resultado',
            name='resposta_usuario',
        ),
        migrations.AddField(
            model_name='resultado',
            name='acerto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resultado',
            name='alternativa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='core.alternativa'),
        ),
        migrations.AddField(
            model_name='resultado',
            name='questao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='core.questoes'),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to=settings.AUTH_USER_MODEL),
        ),
    ]
